console.log(typeof undefined);       // "undefined"
console.log(typeof true);            // "boolean"
console.log(typeof "Hello, world!"); // "string"
console.log(typeof 3.1415926);       // "number"
console.log(typeof {});              // "object"
console.log(typeof null);            // "object"
console.log(typeof console.log);     // "function"
console.log(typeof 1n);              // "bigint"
console.log(typeof Symbol("foo"));   // "symbol"